#
# More configuration examples at:
# http://jekyllrb.com/docs/configuration/
#

#
# Jekyll basic configurations
#

source:         _app
destination:    _site
timezone:       Canada/Eastern
permalink:      /:title.html
markdown:       kramdown
highlighter:    rouge
include:        ["_pages"]
exclude:        ["_pages/themes"]

#
# Jekyll serve settings
#

port:           4321

#
# Jekyll build settings
#

future:         false

#
# Additional Markdown settings
#

kramdown:
  input:                     GFM
  auto_ids:                  true
  footnote_nr:               1
  entity_output:             as_char
  toc_levels:                1..6
  smart_quotes:              lsquo,rsquo,ldquo,rdquo
  enable_coderay:            false
  hard_wrap:                 false
  syntax_highlighter:        rouge
  transliterated_header_ids: true
  footnote_backlink:         "&#8617;&#xfe0e;"

#
# Jekyll plugins
#

gems:
  - jekyll-last-modified-at

#
# Almace Scaffolding settings
#

# Development mode
dev:            false

# Site name
name:          QuinnFTW.com 

# Site description, will appear in the document meta and Atom feed subtitle
description:    QuinnFTW.com - Quinn Perfetto

# CSS path used in templates
# Default:      /assets
assets:         /assets

# Define your main feed URL, this will be only used in your templates
# Default:      /feed.xml
feed:           /feed.xml

# Used in atom feed, sitemap, Twitter Cards, and etc. I should use absolute full URLs for these fields
url:            http://quinnftw.com

# Media assets URL used in posts, without trailing slash. ie. `<img src="{{ site.file }}/image.png">`. In the most cases this URL should be powered by a CDN provider
file:           /assets

# Force UTF-8 encoding, enable this will simply add <meta charset="utf-8"> to the head of your pages
# Default:      false
force_utf_8:    true

# Enable this settings to make your feed Daring Fireball-like link blog
# (This basically change your <link> value to external link you defined in your posts)
# Default:      false
link_blog:      false

# Change the value to true to use post excerpt for RSS feeds
# Default:      false
rss_excerpt:    false

# Show generator credits
# Default:      true
credits:        false

# Items in robots.txt
# For example:
# robots:
#   - "User-agent: *"
#   - "Disallow: /ajax/"
#   - "Disallow: /@async"
#   - "Disallow: /log/"
# Default:      "User-agent: *"
robots:         "User-agent: *"
amsf_theme_base: "themes/curtana"

theme: "curtana"
